---
name: peka
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.0-116.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  salomon_bottom_bar: ^3.1.0
  equatable: ^2.0.3
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^10.1.0
  image_picker: ^0.8.4+4
  loading_overlay: ^0.3.0
  google_maps_flutter: ^2.1.1
  location: ^4.3.0
  geocoding: ^2.0.1
  http: ^0.13.4
  url_launcher: ^6.0.15
  file_picker: ^4.2.7
  responsive_grid: ^2.0.0
  flutter_image_compress: ^1.0.0-nullsafety
  lottie: ^1.2.1
  path_provider: ^2.0.8
  dropdown_search: ^2.0.1
  cherry_toast: ^1.0.2
  timeago: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
  - assets/raw/
